CXX = g++						             
CXXFLAGS = -std=c++14 -g 	 
LDFLAGS =						            

cripto:  cripto.o funciones_cripto.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)


.PHONY: all clean


	$(CXX) $(CXXFLAGS) -c $<

